name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Show working directory (debug)
        run: |
          pwd
          ls -R

      - name: Upgrade pip & install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show pytest version (debug)
        run: python -m pytest --version

      - name: Run tests (verbose)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: python -m pytest -vv
