name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1

      - name: Placeholder deploy step
        if: ${{ success() }}
        run: echo "Deployment successful!"
